package oyun.masa

object GreatPlayer {
  val womenSinger: Map[String, String] = Map(
    "Ajda Pekkan" -> "Ajda_Pekkan",
    "Ajlan Büyükburç" -> "Ajlan_B%C3%BCy%C3%BCkbur%C3%A7",
    "Demet Akalın" -> "Demet_Akal%C4%B1n",
    "İlkay Akkaya" -> "%C4%B0lkay_Akkaya",
    "Akrep Nalan" -> "Akrep_Nalan",
    "Ayla Algan" -> "Ayla_Algan",
    "Tuğba Altıntop" -> "Tu%C4%9Fba_Alt%C4%B1ntop",
    "Arzu Ece" -> "Arzu_Ece",
    "Aslı Gökyokuş" -> "Asl%C4%B1_G%C3%B6kyoku%C5%9F",
    "Aslı Güngör" -> "Asl%C4%B1_G%C3%BCng%C3%B6r",
    "Aslı Hünel" -> "Asl%C4%B1_H%C3%BCnel",
    "Asu Maralman" -> "Asu_Maralman",
    "Asya (şarkıcı)" -> "Asya_(%C5%9Fark%C4%B1c%C4%B1)",
    "Atiye" -> "Atiye",
    "Hülya Avşar" -> "H%C3%BClya_Av%C5%9Far",
    "Aydilge" -> "Aydilge",
    "Ayla Dikmen" -> "Ayla_Dikmen",
    "Aylin Aslım" -> "Aylin_Asl%C4%B1m",
    "Aylin Coşkun" -> "Aylin_Co%C5%9Fkun",
    "Aylin Urgal" -> "Aylin_Urgal",
    "Aylin Vatankoş" -> "Aylin_Vatanko%C5%9F",
    "Aynur Aydın" -> "Aynur_Ayd%C4%B1n",
    "Aynur Doğan" -> "Aynur_Do%C4%9Fan",
    "Aysun Gültekin" -> "Aysun_G%C3%BCltekin",
    "Aysun Kocatepe" -> "Aysun_Kocatepe",
    "Ayta Sözeri" -> "Ayta_S%C3%B6zeri",
    "Ayten Alpman" -> "Ayten_Alpman",
    "Ayça Tekindor" -> "Ay%C3%A7a_Tekindor",
    "Ayça Şen" -> "Ay%C3%A7a_%C5%9Een",
    "Ayşe Birgül Yılmaz" -> "Ay%C5%9Fe_Birg%C3%BCl_Y%C4%B1lmaz",
    "Ayşe Hatun Önal" -> "Ay%C5%9Fe_Hatun_%C3%96nal",
    "Ayşe Özyılmazel" -> "Ay%C5%9Fe_%C3%96zy%C4%B1lmazel",
    "Ayşegül Aldinç" -> "Ay%C5%9Feg%C3%BCl_Aldin%C3%A7",
    "Ayşegül Yordam" -> "Ay%C5%9Feg%C3%BCl_Yordam",
    "Azize Gencebay" -> "Azize_Gencebay",
    "Aşkın Nur Yengi" -> "A%C5%9Fk%C4%B1n_Nur_Yengi",
    "Banu Kırbağ" -> "Banu_K%C4%B1rba%C4%9F",
    "Belkıs Özener" -> "Belk%C4%B1s_%C3%96zener",
    "Bendeniz" -> "Bendeniz",
    "Bengü" -> "Beng%C3%BC",
    "Bergen (şarkıcı)" -> "Bergen_(%C5%9Fark%C4%B1c%C4%B1)",
    "Semiha Berksoy" -> "Semiha_Berksoy",
    "Beyza Durmaz" -> "Beyza_Durmaz",
    "Bilgen Bengü" -> "Bilgen_Beng%C3%BC",
    "Bilgesu Erenus" -> "Bilgesu_Erenus",
    "Birsen Tezer" -> "Birsen_Tezer",
    "Buket Bengisu" -> "Buket_Bengisu",
    "Burcu Güneş" -> "Burcu_G%C3%BCne%C5%9F",
    "Zeynep Casalini" -> "Zeynep_Casalini",
    "Cemile Cevher Çiçek" -> "Cemile_Cevher_%C3%87i%C3%A7ek",
    "Cemre Kemer" -> "Cemre_Kemer",
    "Ceylan Ertem" -> "Ceylan_Ertem",
    "Ceynur" -> "Ceynur",
    "Cihan Güçlü" -> "Cihan_G%C3%BC%C3%A7l%C3%BC",
    "Demet Sağıroğlu" -> "Demet_Sa%C4%9F%C4%B1ro%C4%9Flu",
    "Betül Demir" -> "Bet%C3%BCl_Demir",
    "Deniz Arcak" -> "Deniz_Arcak",
    "Deniz Türkali" -> "Deniz_T%C3%BCrkali",
    "Deniz Özbey" -> "Deniz_%C3%96zbey",
    "Deniz Ünel" -> "Deniz_%C3%9Cnel",
    "Diclehan Baban" -> "Diclehan_Baban",
    "Dilber Ay" -> "Dilber_Ay",
    "Dilek Pınar" -> "Dilek_P%C4%B1nar",
    "Zeynep Dizdar" -> "Zeynep_Dizdar",
    "Doğanay" -> "Do%C4%9Fanay",
    "Ebru Gündeş" -> "Ebru_G%C3%BCnde%C5%9F",
    "Ebru Yaşar" -> "Ebru_Ya%C5%9Far",
    "Ece Anlı" -> "Ece_Anl%C4%B1",
    "Ece Gürsel" -> "Ece_G%C3%BCrsel",
    "Ece Seçkin" -> "Ece_Se%C3%A7kin",
    "Efsun (şarkıcı)" -> "Efsun_(%C5%9Fark%C4%B1c%C4%B1)",
    "Elif Çağlar" -> "Elif_%C3%87a%C4%9Flar",
    "Emel Büyükburç" -> "Emel_B%C3%BCy%C3%BCkbur%C3%A7",
    "Emel Müftüoğlu" -> "Emel_M%C3%BCft%C3%BCo%C4%9Flu",
    "Emel Sayın" -> "Emel_Say%C4%B1n",
    "Candan Erçetin" -> "Candan_Er%C3%A7etin",
    "Sertab Erener" -> "Sertab_Erener",
    "Bülent Ersoy" -> "B%C3%BClent_Ersoy",
    "Esengül" -> "Eseng%C3%BCl",
    "Esin Afşar" -> "Esin_Af%C5%9Far",
    "Esmeray" -> "Esmeray",
    "Esra İçöz" -> "Esra_%C4%B0%C3%A7%C3%B6z",
    "Yonca Evcimik" -> "Yonca_Evcimik",
    "Evlin Bahceban" -> "Evlin_Bahceban",
    "Fatma Turgut" -> "Fatma_Turgut",
    "Şebnem Ferah" -> "%C5%9Eebnem_Ferah",
    "Feryal Başel" -> "Feryal_Ba%C5%9Fel",
    "Funda Arar" -> "Funda_Arar",
    "Funda Kılıç" -> "Funda_K%C4%B1l%C4%B1%C3%A7",
    "Gaye Aksu" -> "Gaye_Aksu",
    "Gizem Berk" -> "Gizem_Berk",
    "Gökben" -> "G%C3%B6kben",
    "Göksel" -> "G%C3%B6ksel",
    "Gökçe (şarkıcı)" -> "G%C3%B6k%C3%A7e_(%C5%9Fark%C4%B1c%C4%B1)",
    "Gönül Akkor" -> "G%C3%B6n%C3%BCl_Akkor",
    "Gönül Yazar" -> "G%C3%B6n%C3%BCl_Yazar",
    "Gül Erda" -> "G%C3%BCl_Erda",
    "Gülay (şarkıcı)" -> "G%C3%BClay_(%C5%9Fark%C4%B1c%C4%B1)",
    "Gülben Ergen" -> "G%C3%BClben_Ergen",
    "Gülden Mutlu" -> "G%C3%BClden_Mutlu",
    "Gülhan" -> "G%C3%BClhan",
    "Gülistan Okan" -> "G%C3%BClistan_Okan",
    "Güliz Ayla" -> "G%C3%BCliz_Ayla",
    "Gülseren Yıldırım" -> "G%C3%BClseren_Y%C4%B1ld%C4%B1r%C4%B1m",
    "Gülsüm Kamu" -> "G%C3%BCls%C3%BCm_Kamu",
    "Gülçin Ergül" -> "G%C3%BCl%C3%A7in_Erg%C3%BCl",
    "Gülşen" -> "G%C3%BCl%C5%9Fen",
    "Günce Koral" -> "G%C3%BCnce_Koral",
    "Güngör Bayrak" -> "G%C3%BCng%C3%B6r_Bayrak",
    "Güzin Yıldız" -> "G%C3%BCzin_Y%C4%B1ld%C4%B1z",
    "Hacer Kirişçi" -> "Hacer_Kiri%C5%9F%C3%A7i",
    "Hadise" -> "Hadise",
    "Hamiyet Yüceses" -> "Hamiyet_Y%C3%BCceses",
    "Harika Avcı" -> "Harika_Avc%C4%B1",
    "Havva Karakaş" -> "Havva_Karaka%C5%9F",
    "Hazal Selçuk" -> "Hazal_Sel%C3%A7uk",
    "Hülya Polat" -> "H%C3%BClya_Polat",
    "Hümeyra" -> "H%C3%BCmeyra",
    "Hüner Coşkuner" -> "H%C3%BCner_Co%C5%9Fkuner",
    "Işıl German" -> "I%C5%9F%C4%B1l_German",
    "Işıl Yücesoy" -> "I%C5%9F%C4%B1l_Y%C3%BCcesoy",
    "Işın Karaca" -> "I%C5%9F%C4%B1n_Karaca",
    "Jale Bekar" -> "Jale_Bekar",
    "Jehan Barbur" -> "Jehan_Barbur",
    "Kader (şarkıcı)" -> "Kader_(%C5%9Fark%C4%B1c%C4%B1)",
    "Mircan Kaya" -> "Mircan_Kaya",
    "Kendi" -> "Kendi",
    "Kibariye" -> "Kibariye",
    "Kıvılcım (şarkıcı)" -> "K%C4%B1v%C4%B1lc%C4%B1m_(%C5%9Fark%C4%B1c%C4%B1)",
    "Kolera (müzisyen)" -> "Kolera_(m%C3%BCzisyen)",
    "Kâmuran Akkor" -> "K%C3%A2muran_Akkor",
    "Lale Belkıs" -> "Lale_Belk%C4%B1s",
    "Leman Sam" -> "Leman_Sam",
    "Lerzan Mutlu" -> "Lerzan_Mutlu",
    "Leyla Gencer" -> "Leyla_Gencer",
    "Linet" -> "Linet",
    "Makbule Kaya" -> "Makbule_Kaya",
    "Maria Rita Epik" -> "Maria_Rita_Epik",
    "Masis Aram Gözbek" -> "Masis_Aram_G%C3%B6zbek",
    "Mediha Demirkıran" -> "Mediha_Demirk%C4%B1ran",
    "Mediha Şen Sancakoğlu" -> "Mediha_%C5%9Een_Sancako%C4%9Flu",
    "Melahat Pars" -> "Melahat_Pars",
    "Melek İrdem" -> "Melek_%C4%B0rdem",
    "Melike Demirağ" -> "Melike_Demira%C4%9F",
    "Melis Danişmend" -> "Melis_Dani%C5%9Fmend",
    "Meral Konrat" -> "Meral_Konrat",
    "Meral Menderes" -> "Meral_Menderes",
    "Merve Özbey" -> "Merve_%C3%96zbey",
    "Meyra" -> "Meyra",
    "Mine Koşan" -> "Mine_Ko%C5%9Fan",
    "Mine Çağlıyan" -> "Mine_%C3%87a%C4%9Fl%C4%B1yan",
    "Mualla Mukadder Atakan" -> "Mualla_Mukadder_Atakan",
    "Muazzez Ersoy" -> "Muazzez_Ersoy",
    "Muhterem Nur" -> "Muhterem_Nur",
    "Müfide İnselel" -> "M%C3%BCfide_%C4%B0nselel",
    "Müzehher Güyer" -> "M%C3%BCzehher_G%C3%BCyer",
    "Müzeyyen Senar" -> "M%C3%BCzeyyen_Senar",
    "Müşerref Akay" -> "M%C3%BC%C5%9Ferref_Akay",
    "Nadide Sultan" -> "Nadide_Sultan",
    "Nazan Öncel" -> "Nazan_%C3%96ncel",
    "Nazan Şoray" -> "Nazan_%C5%9Eoray",
    "Naşide Göktürk" -> "Na%C5%9Fide_G%C3%B6kt%C3%BCrk",
    "Nesrin Sipahi" -> "Nesrin_Sipahi",
    "Nez" -> "Nez",
    "Neşe Karaböcek" -> "Ne%C5%9Fe_Karab%C3%B6cek",
    "Nigar Uluerer" -> "Nigar_Uluerer",
    "Nil Karaibrahimgil" -> "Nil_Karaibrahimgil",
    "Nil Ünal" -> "Nil_%C3%9Cnal",
    "Nilgül Badakal" -> "Nilg%C3%BCl_Badakal",
    "Nilgün Atılgan" -> "Nilg%C3%BCn_At%C4%B1lgan",
    "Nilüfer (şarkıcı)" -> "Nil%C3%BCfer_(%C5%9Fark%C4%B1c%C4%B1)",
    "Nilüfer Akbal" -> "Nil%C3%BCfer_Akbal",
    "Nonna Bella" -> "Nonna_Bella",
    "Nur Yoldaş" -> "Nur_Yolda%C5%9F",
    "Nurhan Damcıoğlu" -> "Nurhan_Damc%C4%B1o%C4%9Flu",
    "Nâlân" -> "N%C3%A2l%C3%A2n",
    "Nükhet Duru" -> "N%C3%BCkhet_Duru",
    "Nükhet Ruacan" -> "N%C3%BCkhet_Ruacan",
    "Zuhal Olcay" -> "Zuhal_Olcay",
    "Füsun Önal" -> "F%C3%BCsun_%C3%96nal",
    "Oya Küçümen" -> "Oya_K%C3%BC%C3%A7%C3%BCmen",
    "Eda Özülkü" -> "Eda_%C3%96z%C3%BClk%C3%BC",
    "Pamela Spence" -> "Pamela_Spence",
    "Parla Şenol" -> "Parla_%C5%9Eenol",
    "Pelin Sönmez" -> "Pelin_S%C3%B6nmez",
    "Pınar Ayhan" -> "P%C4%B1nar_Ayhan",
    "Pınar Aylin" -> "P%C4%B1nar_Aylin",
    "Pınar Soykan" -> "P%C4%B1nar_Soykan",
    "Rana Alagöz" -> "Rana_Alag%C3%B6z",
    "Rengin (şarkıcı)" -> "Rengin_(%C5%9Fark%C4%B1c%C4%B1)",
    "Reyhan Karaca" -> "Reyhan_Karaca",
    "Rojin" -> "Rojin",
    "Romalı Perihan" -> "Romal%C4%B1_Perihan",
    "Sabahat Akkiraz" -> "Sabahat_Akkiraz",
    "Sabite Tur Gülerman" -> "Sabite_Tur_G%C3%BClerman",
    "Safiye Soyman" -> "Safiye_Soyman",
    "Şevval Sam" -> "%C5%9Eevval_Sam",
    "Defne Samyeli" -> "Defne_Samyeli",
    "Seden Gürel" -> "Seden_G%C3%BCrel",
    "Sefa Topsakal" -> "Sefa_Topsakal"
  )

  val menSinger: Map[String, String] = Map(
    "Manço" -> "Barış_Manço"
  )

  val all = womenSinger ++ menSinger

  private val size = all.size
  private val names = all.keys.toVector

  def randomName: String = names(scala.util.Random nextInt size)

  def wikiUrl(name: String) = all get name map { s =>
    // s"https://tr.wikipedia.org/wiki/$s"
    s"https://www.google.com/search?q=$s"
  }
}
